function [figureHandle] = numericVectorDataInputGUI(tempNumericVector,tempNumericVectorVariableFlag,nameOfTheVector)
    
    if nargin < 1
        tempNumericVector = [1:100];
    end
    if nargin < 2
        tempNumericVectorVariableFlag = 0*tempNumericVector;
    end
    if nargin < 2
        nameOfTheVector = 'Untitled Numeric Vector';
    end    
    
    % Save initial values
    setappdata(0,'tempNumericVector',tempNumericVector);
    setappdata(0,'tempNumericVectorVariableFlag',tempNumericVectorVariableFlag);
    
    % Convert to a column vector
    tempNumericVector = tempNumericVector(:);
    tempNumericVectorVariableFlag = tempNumericVectorVariableFlag(:);
    initialData = num2cell([tempNumericVector,tempNumericVectorVariableFlag]);
    
    fontSize = 12;
    fontName = 'FixedWidth';
    
    figureHandle = figure( ...
        'Tag', 'numericVectorDataInputGUI', ...
        'Units', 'normalized', ...
        'Position',[0.4,0.3,0.2,0.4],...
        'Name', nameOfTheVector, ...
        'MenuBar', 'none', ...
        'NumberTitle', 'off', ...
        'Color', get(0,'DefaultUicontrolBackgroundColor'), ...
        'WindowStyle','Modal');
    tblNumericVectorData = uitable('Parent',figureHandle,...
        'FontSize',fontSize,'FontName', fontName,'units','normalized','Position',[0 0.1 1 0.7]);
    
    columnName = {'Value', 'Variable'};
    columnFormat = {'numeric', 'numeric'};
    columnWidth =  {150, 50};
    columnEditable = [true false];
    set(tblNumericVectorData ,'ColumnFormat',columnFormat,'ColumnEditable', columnEditable,...
        'ColumnName', columnName,'ColumnWidth',columnWidth,'Data',initialData,...
        'CellEditCallback',{@tblNumericVectorData_CellEditCallback},...
        'CellSelectionCallback',{@tblNumericVectorData_CellSelectionCallback});
    
    txtNumberOfRows = uicontrol( ...
        'Parent',figureHandle,...
        'Units', 'Normalized', ...
        'FontSize',fontSize,'FontName', fontName,...
        'Style','edit',...
        'Tag', 'txtNumberOfRows', ...
        'String','10',...
        'Units', 'normalized', ...
        'Position',[0.43,0.92,0.14,0.05]);
    
    btnAdd = uicontrol( ...
        'Parent',figureHandle,...
        'FontSize',fontSize,'FontName', fontName,...
        'Style','pushbutton',...
        'Tag', 'btnAdd', ...
        'String','Add',...
        'Units', 'normalized', ...
        'Position',[0.2,0.92,0.2,0.05],......
        'Callback',{@btnAdd_Callback,tblNumericVectorData,txtNumberOfRows});
    
    btnRemove = uicontrol( ...
        'Parent',figureHandle,...
        'Units', 'Normalized', ...
        'FontSize',fontSize,'FontName', fontName,...
        'Style','pushbutton',...
        'Tag', 'btnRemove', ...
        'String','Remove',...
        'Units', 'normalized', ...
        'Position',[0.6,0.92,0.2,0.05],...
        'Callback',{@btnRemove_Callback,tblNumericVectorData,txtNumberOfRows});
     
    
    
    lblNote = uicontrol( ...
        'Parent',figureHandle,...
        'Units', 'Normalized', ...
        'FontSize',fontSize,'FontName', fontName,...
        'Style','text',...
        'Tag', 'lblNote', ...
        'String','(Numbers are added to/removed from the last row)',...
        'Units', 'normalized', ...
        'Position',[0.02,0.82,0.9,0.08]);

    
    btnImport = uicontrol( ...
        'Parent',figureHandle,...
        'FontSize',fontSize,'FontName', 'FixedWidth',...
        'Style','pushbutton',...
        'Tag', 'btnImport', ...
        'String','Import',...
        'Units', 'normalized', ...
        'Position',[0.1,0.02,0.2,0.05],...
        'Callback',{@btnImport_Callback,tblNumericVectorData});
    
    btnOk = uicontrol( ...
        'Parent',figureHandle,...
        'FontSize',fontSize,'FontName', 'FixedWidth',...
        'Style','pushbutton',...
        'Tag', 'btnOk', ...
        'String','OK',...
        'Units', 'normalized', ...
        'Position',[0.4,0.02,0.2,0.05],...
        'Callback',{@btnOk_Callback,tblNumericVectorData,figureHandle});
    
    
    btnCancel = uicontrol( ...
        'Parent',figureHandle,...
        'Units', 'Normalized', ...
        'FontSize',fontSize,'FontName', 'FixedWidth',...
        'Style','pushbutton',...
        'Tag', 'btnCancel', ...
        'String','Cancel',...
        'Units', 'normalized', ...
        'Position',[0.7,0.02,0.2,0.05],...
        'Callback',{@btnCancel_Callback,tblNumericVectorData,figureHandle});
    
    
end

function tblNumericVectorData_CellSelectionCallback(hObject, eventdata)
end
function tblNumericVectorData_CellEditCallback(hObject, eventdata)
end
function btnAdd_Callback(~, ~, tblNumericVectorData,txtNumberOfRows)
    tableData = get(tblNumericVectorData,'Data');
    additionalRows = str2num(get(txtNumberOfRows,'String'));
    if ~isempty(additionalRows)
        newRows = num2cell(zeros(additionalRows,2));
        tableDataNew = [tableData;newRows];
    else
        tableDataNew = tableData;
    end
    set(tblNumericVectorData,'Data',tableDataNew);
end
function btnRemove_Callback(~, ~, tblNumericVectorData,txtNumberOfRows)
    tableData = get(tblNumericVectorData,'Data');
    deleteRows = str2num(get(txtNumberOfRows,'String'));
    if ~isempty(deleteRows)
        lastRow = size(tableData,1) - deleteRows;
        if lastRow <= 0
            tableDataNew = '';
        else
            tableDataNew = tableData(1:lastRow,:);
        end
    else
        tableDataNew = tableData;
    end
    set(tblNumericVectorData,'Data',tableDataNew);
end
function btnImport_Callback(~, ~, tblNumericVectorData)
end
function btnOk_Callback(~, ~, tblNumericVectorData,figureHandle)
    tableDataNumeric = cell2mat(get(tblNumericVectorData,'Data'));
    if ~isempty(tableDataNumeric)
        tempNumericVector = tableDataNumeric(:,1);
        tempNumericVectorVariableFlag = tableDataNumeric(:,2);
    else
        tempNumericVector = [];
        tempNumericVectorVariableFlag = [];
    end
    setappdata(0,'tempNumericVector',tempNumericVector);
    setappdata(0,'tempNumericVectorVariableFlag',tempNumericVectorVariableFlag);
    
    close(figureHandle);
end
function btnCancel_Callback(~, ~, tblNumericVectorData,figureHandle)
    % Do nothing 
    close(figureHandle);
end
