function mainFigHandle = SelectMultiConfigurationVariable(optSystem,fontName,fontSize);
    %SelectMultiConfigurationVariable Displays a dilog box which is used to
    
    % Inputs:
    %   ( optSystem,fontName,fontSize )
    % Outputs:
    %   [ ]
    
    % <<<<<<<<<<<<<<<<<<<<<<<<< Author Section >>>>>>>>>>>>>>>>>>>>>>>>>>>>
    %   Written By: Worku, Norman Girma
    %   Advisor: Prof. Herbert Gross
    %	Optical System Design and Simulation Research Group
    %   Institute of Applied Physics
    %   Friedrich-Schiller-University of Jena
    
    % <<<<<<<<<<<<<<<<<<< Change History Section >>>>>>>>>>>>>>>>>>>>>>>>>>
    % Date----------Modified By ---------Modification Detail--------Remark
    % Oct 25,2015   Worku, Norman G.     Original Version
    
    
    % Default Input
    if nargin < 1
        % Get default optical system
        optSystem = OpticalSystem();
    end
    if nargin < 2
        fontSize = 9.5;
    end
    if nargin < 3
        fontName = 'FixedWidth';
    end
    
    figureHandle = ObjectHandle(struct());
    figureHandle.Object.OpticalSystem = optSystem;
    figureHandle.Object.MainFigureHandle = figure( ...
        'Tag', 'MainFigureHandle', ...
        'Units','Normalized',...
        'Position', [0.35,0.35,0.3,0.3], ...
        'Name', 'Multi-Configuration Variable Selector', ... %'WindowStyle','Modal',...
        'MenuBar', 'none', ...
        'NumberTitle', 'off', ...%'WindowStyle','Modal',...
        'Color', get(0,'DefaultUicontrolBackgroundColor'),...
        'CloseRequestFcn',{@figureCloseRequestFunction,figureHandle});
    mainFigHandle = figureHandle.Object.MainFigureHandle;
    
    
    % Creation of all uicontrols
    
    % -----------------------------------------------------------------
    figureHandle.Object.lblMultiConfigurationVariableCategory = uicontrol( ...
        'Parent', figureHandle.Object.MainFigureHandle, ...
        'Tag', 'lblMultiConfigurationVariableCategory', ...
        'Style', 'text', ...
        'HorizontalAlignment','left',...
        'Units','Normalized',...
        'Position', [0.02,0.8,0.48,0.10], ...
        'fontSize',fontSize,...
        'FontName',fontName,...
        'String', 'Variable Category');
    
    MultiConfigurationVariableCategory = {'System Data','Element Data'};
    figureHandle.Object.popMultiConfigurationVariableCategory = uicontrol( ...
        'Parent', figureHandle.Object.MainFigureHandle, ...
        'Tag', 'popMultiConfigurationVariableCategory', ...
        'Style', 'popupmenu', ...
        'fontSize',fontSize,...
        'FontName',fontName,...
        'HorizontalAlignment','left',...
        'Units','Normalized',...
        'Position', [0.50,0.8,0.48,0.1], ...
        'BackgroundColor', [1 1 1],...
        'String',MultiConfigurationVariableCategory,...
        'Value',1);
    % -----------------------------------------------------------------
    figureHandle.Object.lblMultiConfigurationElementIndex = uicontrol( ...
        'Parent', figureHandle.Object.MainFigureHandle, ...
        'Tag', 'lblMultiConfigurationElementIndex', ...
        'Style', 'text', ...
        'HorizontalAlignment','left',...
        'Units','Normalized',...
        'Position', [0.02,0.65,0.48,0.1], ...
        'fontSize',fontSize,...
        'FontName',fontName,...
        'String', 'Element Index');
    
    
    MultiConfigurationVariableFieldOrIndex1 = num2cell([1:length(optSystem.OpticalElementArray)]);
    figureHandle.Object.popMultiConfigurationElementIndex = uicontrol( ...
        'Parent', figureHandle.Object.MainFigureHandle, ...
        'Tag', 'popMultiConfigurationElementIndex', ...
        'Style', 'popupmenu', ...
        'fontSize',fontSize,...
        'FontName',fontName,...
        'HorizontalAlignment','left',...
        'Units','Normalized',...
        'Position', [0.50,0.65,0.48,0.1], ...
        'BackgroundColor', [1 1 1],...
        'String',MultiConfigurationVariableFieldOrIndex1,...
        'Value',1,'enable','off');
    % -----------------------------------------------------------------
    figureHandle.Object.lblMultiConfigurationVariable = uicontrol( ...
        'Parent', figureHandle.Object.MainFigureHandle, ...
        'Tag', 'lblMultiConfigurationVariable', ...
        'Style', 'text', ...
        'HorizontalAlignment','left',...
        'Units','Normalized',...
        'Position', [0.02,0.5,0.48,0.1], ...
        'fontSize',fontSize,...
        'FontName',fontName,...
        'String', 'Variable Name');
    
    MultiConfigurationVariable = getOpticalSystemMultiConfigurationVariables( optSystem );
    figureHandle.Object.popMultiConfigurationVariable = uicontrol( ...
        'Parent', figureHandle.Object.MainFigureHandle, ...
        'Tag', 'popMultiConfigurationVariable', ...
        'Style', 'popupmenu', ...
        'fontSize',fontSize,...
        'FontName',fontName,...
        'HorizontalAlignment','left',...
        'Units','Normalized',...
        'Position', [0.50,0.5,0.48,0.1], ...
        'BackgroundColor', [1 1 1],...
        'String',MultiConfigurationVariable,...
        'Value',1);
    
    % -----------------------------------------------------------------
    figureHandle.Object.lblMultiConfigurationVariableFieldOrIndex1 = uicontrol( ...
        'Parent', figureHandle.Object.MainFigureHandle, ...
        'Tag', 'lblMultiConfigurationVariableFieldOrIndex1', ...
        'Style', 'text', ...
        'HorizontalAlignment','left',...
        'Units','Normalized',...
        'Position', [0.02,0.35,0.48,0.1], ...
        'fontSize',fontSize,...
        'FontName',fontName,...
        'String', 'Unused');
    
    MultiConfigurationVariableFieldOrIndex1 = {'1'};
    figureHandle.Object.popMultiConfigurationVariableFieldOrIndex1 = uicontrol( ...
        'Parent', figureHandle.Object.MainFigureHandle, ...
        'Tag', 'popMultiConfigurationVariableFieldOrIndex1', ...
        'Style', 'popupmenu', ...
        'fontSize',fontSize,...
        'FontName',fontName,...
        'HorizontalAlignment','left',...
        'Units','Normalized',...
        'Position', [0.50,0.35,0.48,0.1], ...
        'BackgroundColor', [1 1 1],...
        'String',MultiConfigurationVariableFieldOrIndex1,...
        'Value',1,'enable','off');
    % -----------------------------------------------------------------
    figureHandle.Object.lblMultiConfigurationVariableFieldOrIndex2 = uicontrol( ...
        'Parent', figureHandle.Object.MainFigureHandle, ...
        'Tag', 'lblMultiConfigurationVariableFieldOrIndex2', ...
        'Style', 'text', ...
        'HorizontalAlignment','left',...
        'Units','Normalized',...
        'Position', [0.02,0.20,0.48,0.1], ...
        'fontSize',fontSize,...
        'FontName',fontName,...
        'String', 'Unused');
    
    MultiConfigurationVariableFieldOrIndex2 = {'1'};
    figureHandle.Object.popMultiConfigurationVariableFieldOrIndex2 = uicontrol( ...
        'Parent', figureHandle.Object.MainFigureHandle, ...
        'Tag', 'popMultiConfigurationVariableFieldOrIndex2', ...
        'Style', 'popupmenu', ...
        'fontSize',fontSize,...
        'FontName',fontName,...
        'HorizontalAlignment','left',...
        'Units','Normalized',...
        'Position', [0.50,0.20,0.48,0.1], ...
        'BackgroundColor', [1 1 1],...
        'String',MultiConfigurationVariableFieldOrIndex2,...
        'Value',1,'enable','off');
    
  % Callbacks
    set(figureHandle.Object.popMultiConfigurationVariableCategory,...
        'Callback',{@popMultiConfigurationVariableCategory_Callback,figureHandle});
    set(figureHandle.Object.popMultiConfigurationElementIndex,...
        'Callback',{@popMultiConfigurationElementIndex_Callback,figureHandle});
    set(figureHandle.Object.popMultiConfigurationVariable,...
        'Callback',{@popMultiConfigurationVariable_Callback,figureHandle});
    set(figureHandle.Object.popMultiConfigurationVariableFieldOrIndex1,...
        'Callback',{@popMultiConfigurationVariableFieldOrIndex1_Callback,figureHandle});
    
    figureHandle.Object.cmdOk = uicontrol( ...
        'Parent', figureHandle.Object.MainFigureHandle, ...
        'Tag', 'cmdOk', ...
        'Style', 'pushbutton', ...
        'Units','Normalized',...
        'Position', [0.5,0.05,0.20,0.10], ...
        'fontSize',fontSize,...
        'FontName',fontName,...
        'String', 'Ok', ...
        'Callback', {@cmdOk_Callback,figureHandle});
    figureHandle.Object.cmdCancel = uicontrol( ...
        'Parent', figureHandle.Object.MainFigureHandle, ...
        'Tag', 'cmdCancel', ...
        'Style', 'pushbutton', ...
        'Units','Normalized',...
        'Position', [0.78,0.05,0.20,0.10], ...
        'fontSize',fontSize,'FontName',fontName,...
        'String', 'Cancel', ...
        'Callback', {@cmdCancel_Callback,figureHandle});
    
    
end
function figureCloseRequestFunction(~,~,figureHandle)
    delete(figureHandle.Object.MainFigureHandle);
end

function popMultiConfigurationVariableCategory_Callback(hObject,~,figureHandle)
    optSystem = figureHandle.Object.OpticalSystem;
    if get(hObject,'Value') == 1 % System data
        [ multiConfigurationVariables ] = ...
            getOpticalSystemMultiConfigurationVariables( optSystem );
        set(figureHandle.Object.popMultiConfigurationVariable,'String',multiConfigurationVariables,'Value',1);
        set(figureHandle.Object.popMultiConfigurationElementIndex,'Value',1,'Enable','off');
        
    elseif get(hObject,'Value') == 2 % Element data
        elemIndex = get(figureHandle.Object.popMultiConfigurationElementIndex,'Value');
        [ multiConfigurationVariables ] = ...
            getOpticalElementMultiConfigurationVariables( optSystem.OpticalElementArray{elemIndex} );
        set(figureHandle.Object.popMultiConfigurationVariable,'String',multiConfigurationVariables,'Value',1);
        set(figureHandle.Object.popMultiConfigurationElementIndex,'Enable','on','Value',1);
        
        popMultiConfigurationElementIndex_Callback(figureHandle.Object.popMultiConfigurationElementIndex,0,figureHandle);
    else
    end
    set(figureHandle.Object.popMultiConfigurationVariableFieldOrIndex1,'String',{''},'Enable','Off','Value',1);
    set(figureHandle.Object.lblMultiConfigurationVariableFieldOrIndex1,'String','Unused');
    set(figureHandle.Object.popMultiConfigurationVariableFieldOrIndex2,'String',{''},'Enable','Off','Value',1);
    set(figureHandle.Object.lblMultiConfigurationVariableFieldOrIndex2,'String','Unused');
end
function popMultiConfigurationElementIndex_Callback(hObject,~,figureHandle)
    optSystem = figureHandle.Object.OpticalSystem;
    elemIndex = get(figureHandle.Object.popMultiConfigurationElementIndex,'Value');
    [ multiConfigurationVariables ] = ...
        getOpticalElementMultiConfigurationVariables( optSystem.OpticalElementArray{elemIndex} );
    set(figureHandle.Object.popMultiConfigurationVariable,'String',multiConfigurationVariables,'Value',1);
    
    set(figureHandle.Object.popMultiConfigurationVariableFieldOrIndex1,'String',{''},'Enable','Off','Value',1);
    set(figureHandle.Object.lblMultiConfigurationVariableFieldOrIndex1,'String','Unused');
    set(figureHandle.Object.popMultiConfigurationVariableFieldOrIndex2,'String',{''},'Enable','Off','Value',1);
    set(figureHandle.Object.lblMultiConfigurationVariableFieldOrIndex2,'String','Unused');
    
    popMultiConfigurationVariable_Callback(figureHandle.Object.popMultiConfigurationVariable,0,figureHandle);
end
function popMultiConfigurationVariable_Callback(hObject,~,figureHandle)
    optSystem = figureHandle.Object.OpticalSystem;
    elemIndex = get(figureHandle.Object.popMultiConfigurationElementIndex,'Value');
    if get(figureHandle.Object.popMultiConfigurationVariableCategory,'Value') == 1
        [ multiConfigurationVariableList ] = ...
            getOpticalSystemMultiConfigurationVariables( optSystem );
    elseif get(figureHandle.Object.popMultiConfigurationVariableCategory,'Value') == 2
        elemIndex = get(figureHandle.Object.popMultiConfigurationElementIndex,'Value');
        [ multiConfigurationVariableList ] = ...
            getOpticalElementMultiConfigurationVariables( optSystem.OpticalElementArray{elemIndex});
    else
    end
    
    multiConfigurationVariableIndex = get(figureHandle.Object.popMultiConfigurationVariable,'Value');
    selectedVariableName = multiConfigurationVariableList{multiConfigurationVariableIndex};
    switch lower(selectedVariableName)
        % System Data
        case lower('WavelengthMatrix')
            set(figureHandle.Object.lblMultiConfigurationVariableFieldOrIndex1,'String','Wavelength Parameter');
            set(figureHandle.Object.popMultiConfigurationVariableFieldOrIndex1,'String',{'Wavelength','Weight'},'Enable','On');
            
            nWavelength = getNumberOfWavelengths( optSystem );
            set(figureHandle.Object.lblMultiConfigurationVariableFieldOrIndex2,'String','Index');
            set(figureHandle.Object.popMultiConfigurationVariableFieldOrIndex2,'String',num2cell([1:nWavelength]),'Enable','On');
            
        case lower('FieldPointMatrix')
            set(figureHandle.Object.lblMultiConfigurationVariableFieldOrIndex1,'String','Field Point Parameter');
            set(figureHandle.Object.popMultiConfigurationVariableFieldOrIndex1,'String',{'Field X','Field Y','Weight'},'Enable','On');
            
            nFieldPoints = getNumberOfFieldPoints( optSystem );
            set(figureHandle.Object.lblMultiConfigurationVariableFieldOrIndex2,'String','Index');
            set(figureHandle.Object.popMultiConfigurationVariableFieldOrIndex2,'String',num2cell([1:nFieldPoints]),'Enable','On');
            
            
            % Now the surface parameters
        case lower('Aperture')
%             set(figureHandle.Object.lblMultiConfigurationVariableFieldOrIndex1,'String','Aperture Parameter');
%             surfAperture = optSystem.OpticalElementArray{elemIndex}.Aperture;
%             [ apertureParametersList ] = ...
%                 getSurfaceApertureMultiConfigurationVariables( surfAperture );
%             set(figureHandle.Object.popMultiConfigurationVariableFieldOrIndex1,'String',apertureParametersList,'Enable','On');
%             popMultiConfigurationVariableFieldOrIndex1_Callback(figureHandle.Object.popMultiConfigurationVariableFieldOrIndex1,0,figureHandle);
        case lower('ExtraData')
            set(figureHandle.Object.lblMultiConfigurationVariableFieldOrIndex1,'String','Extra Data Index');
            surfExtraData = optSystem.OpticalElementArray{elemIndex}.ExtraData;
            
            set(figureHandle.Object.popMultiConfigurationVariableFieldOrIndex1,'String',num2cell([1:length(surfExtraData)]),'Enable','On');
            popMultiConfigurationVariableFieldOrIndex1_Callback(figureHandle.Object.popMultiConfigurationVariableFieldOrIndex1,0,figureHandle);
        case lower('Grating')
%             set(figureHandle.Object.lblMultiConfigurationVariableFieldOrIndex1,'String','Grating Parameter');
%             surfGrating = optSystem.OpticalElementArray{elemIndex}.Grating;
%             [ gratingParametersList ] = ...
%                 getGratingMultiConfigurationVariables( surfGrating );
%             set(figureHandle.Object.popMultiConfigurationVariableFieldOrIndex1,'String',gratingParametersList,'Enable','On');
%             popMultiConfigurationVariableFieldOrIndex1_Callback(figureHandle.Object.popMultiConfigurationVariableFieldOrIndex1,0,figureHandle);
        case lower('Tilt')
            set(figureHandle.Object.lblMultiConfigurationVariableFieldOrIndex1,'String','Tilt In');
            
            set(figureHandle.Object.popMultiConfigurationVariableFieldOrIndex1,'String',{'X','Y','Z'},'Enable','On');
            popMultiConfigurationVariableFieldOrIndex1_Callback(figureHandle.Object.popMultiConfigurationVariableFieldOrIndex1,0,figureHandle);
        case lower('Decenter')
            set(figureHandle.Object.lblMultiConfigurationVariableFieldOrIndex1,'String','Decenter In');
            
            set(figureHandle.Object.popMultiConfigurationVariableFieldOrIndex1,'String',{'X','Y'},'Enable','On');
            popMultiConfigurationVariableFieldOrIndex1_Callback(figureHandle.Object.popMultiConfigurationVariableFieldOrIndex1,0,figureHandle);
            
        otherwise
            set(figureHandle.Object.popMultiConfigurationVariableFieldOrIndex1,'String',{''},'Enable','Off','Value',1);
            set(figureHandle.Object.lblMultiConfigurationVariableFieldOrIndex1,'String','Unused');
            set(figureHandle.Object.popMultiConfigurationVariableFieldOrIndex2,'String',{''},'Enable','Off','Value',1);
            set(figureHandle.Object.lblMultiConfigurationVariableFieldOrIndex2,'String','Unused');
            popMultiConfigurationVariableFieldOrIndex1_Callback(figureHandle.Object.popMultiConfigurationVariableFieldOrIndex1,0,figureHandle);
    end
    
    
end
function popMultiConfigurationVariableFieldOrIndex1_Callback(hObject,~,figureHandle)
    optSystem = figureHandle.Object.OpticalSystem;
    elemIndex = get(figureHandle.Object.popMultiConfigurationElementIndex,'Value');
    if get(figureHandle.Object.popMultiConfigurationVariableCategory,'Value') == 1
        [ multiConfigurationVariableList ] = ...
            getOpticalSystemMultiConfigurationVariables( optSystem );
    elseif get(figureHandle.Object.popMultiConfigurationVariableCategory,'Value') == 2
        elemIndex = get(figureHandle.Object.popMultiConfigurationElementIndex,'Value');
        [ multiConfigurationVariableList ] = ...
            getOpticalElementMultiConfigurationVariables( optSystem.OpticalElementArray{elemIndex} );
    else
    end
    
    multiConfigurationVariableIndex = get(figureHandle.Object.popMultiConfigurationVariable,'Value');
    selectedVariableName = multiConfigurationVariableList{multiConfigurationVariableIndex};
    switch lower(selectedVariableName)
        % System Data
        case lower('WavelengthMatrix')
         
        case lower('FieldPointMatrix')

            % Now the surface parameters
        case lower('Aperture')
%             apertureParameterList  = get(figureHandle.Object.popMultiConfigurationVariableFieldOrIndex1,'String');
%             apertureParameterIndex = get(figureHandle.Object.popMultiConfigurationVariableFieldOrIndex1,'Value');
%             selectedApertureParameterName = apertureParameterList{apertureParameterIndex};
%             switch lower(selectedApertureParameterName)
%                 case lower('Decenter')
%                     set(figureHandle.Object.popMultiConfigurationVariableFieldOrIndex2,'String',{'X','Y'},'Enable','On');
%                     set(figureHandle.Object.lblMultiConfigurationVariableFieldOrIndex2,'String','Decenter In ');
%                 otherwise
%                     set(figureHandle.Object.popMultiConfigurationVariableFieldOrIndex2,'String',{''},'Enable','Off','Value',1);
%                     set(figureHandle.Object.lblMultiConfigurationVariableFieldOrIndex2,'String','Unused');
%             end
        case lower('ExtraData')

        case lower('Grating')

        case lower('Tilt')

        case lower('Decenter')
 
        otherwise
            set(figureHandle.Object.popMultiConfigurationVariableFieldOrIndex1,'String',{''},'Enable','Off','Value',1);
            set(figureHandle.Object.lblMultiConfigurationVariableFieldOrIndex1,'String','Unused');
            set(figureHandle.Object.popMultiConfigurationVariableFieldOrIndex2,'String',{''},'Enable','Off','Value',1);
            set(figureHandle.Object.lblMultiConfigurationVariableFieldOrIndex2,'String','Unused');
    end
end
function cmdOk_Callback(~,~,figureHandle)
    % Get Element Index
    variableCategory = get(figureHandle.Object.popMultiConfigurationVariableCategory,'Value');
    if variableCategory == 1 % System data
        elemIndex = 0;
    else
        elemIndex = get(figureHandle.Object.popMultiConfigurationElementIndex,'Value');
    end
    % Get the current MultiConfigurationVariable
    
end

function cmdCancel_Callback(~,~,figureHandle)
end
