function [ multiConfigurationVariables,multiConfigurationVariableFormats ] = ...
        getOpticalSystemMultiConfigurationVariables( optSystem )
    %getOpticalSystemMultiConfigurationVariables Summary of this function goes here
    %   Detailed explanation goes here
%     AllVariables = {'SystemApertureType','SystemApertureValue',...
%         'ComputeFastSemidiameter','LensName','LensNote','WavelengthUnit',...
%         'LensUnit','WavelengthMatrix','PrimaryWavelengthIndex','FieldType',...
%         'FieldPointMatrix','IsObjectAfocal','IsImageAfocal',...
%         'IsObjectTelecenteric','IsImageTelecenteric','ApodizationType',...
%         'ApodizationParameters','FieldNormalization ','SystemMode'};    
    % Return varables which make sense for multiconfiguration
    multiConfigurationVariables = {'SystemApertureValue',...
        'WavelengthMatrix','PrimaryWavelengthIndex','FieldType',...
        'FieldPointMatrix','IsObjectAfocal','IsImageAfocal',...
        'IsObjectTelecenteric','IsImageTelecenteric','FieldNormalization'};
    multiConfigurationVariableFormats = {'numeric',...
        'numeric','numeric','numeric',...
        'numeric','logical','logical',...
        'logical','logical','numeric'};
end

